[package]
name = "bote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
home = "0.5.5"
thiserror = "1.0.48"
tokio = "1.32.0"
veilid-core = "0.2.1"
